#!/usr/bin/env python3
"""Hand-authored focus effects for the DOP core tree."""

from dop_focus_effect_design import (
    Design,
    admin_costs,
    army_xp,
    building,
    china_opinion,
    command_power,
    corruption,
    design,
    gdp_growth,
    japan_approval,
    manpower,
    military_costs,
    misc_costs,
    misc_income,
    pp,
    scw,
    social_costs,
    socdev,
    spend,
    stability,
    stockpile,
    tax,
    war_support,
)


CORE_DESIGN_ROWS: list[tuple[str, Design]] = [
    ("GNG_focus_new_fate_choice_of_gng", design("政治资本/国家认同", "新的十字路口需要执政资源，也正式承认认同困局", pp(35))),
    ("GNG_focus_the_pearl_of_Pan_Asia", design("增长/东京关系/南京关系", "泛亚明珠同时向市场、东京与中国展示成就", gdp_growth("0.18"), japan_approval("2"), china_opinion("1"))),

    # Lee / Cheung Kong: broadly positive welfare-led development.
    ("GNG_focus_warry_from_Li", design("贫困/稳定/社会预算", "李嘉诚以福利和稳定优先，代价是更高长期支出", socdev("improve_poverty_low"), stability("0.02"), social_costs("0.018"))),
    ("GNG_focus_atonement_for_past", design("贫困/医疗/社会预算", "难民住房和医保显著改善生活并扩大社会开支", socdev("improve_poverty_med"), socdev("improve_healthcare_low"), social_costs("0.028"))),
    ("GNG_focus_focus_on_str_commerce", design("小商业/贫困/税制", "街头商业获得生存空间、就业与轻微税务减让", misc_income("0.018"), socdev("improve_poverty_low"), tax("business", "-0.008"))),
    ("GNG_focus_come_back_home", design("农业/工业专长/增长", "产业回流农村，让农业剩余劳动力进入制造业", socdev("improve_agriculture_low"), socdev("improve_industrial_expertise_low"), gdp_growth("0.10"))),
    ("GNG_focus_gng_chemical_industry", design("工业设备/增长/公共健康", "化工反哺制造业，但污染与事故损害健康", socdev("improve_industrial_equipment_low"), gdp_growth("0.12"), socdev("worsen_healthcare_low"))),
    ("GNG_focus_dear_with_pharmaceutical", design("医疗/监管成本", "整顿药企提高医疗水平，也要求持续监管拨款", socdev("improve_healthcare_med"), admin_costs("0.012"))),
    ("GNG_focus_sub_center_in_gng", design("城市建设/贫困/投资", "潮汕副中心承接难民与产业，需先建设办公空间", building(593, "offices", 1, 1), socdev("improve_poverty_low"), spend("0.065"))),
    ("GNG_focus_business_regulation", design("廉洁/稳定/增长", "劳动监管换来信任，却短期压低企业扩张速度", corruption("-1"), stability("0.025"), gdp_growth("-0.04"))),

    # Finance coalition: fiscal and industrial gains paid for by ordinary people.
    ("GNG_focus_t_strategy_of_tycoons", design("增长/贫困/腐败", "财界方案迅速增厚报表，也牺牲劳工和廉洁", gdp_growth("0.16"), socdev("worsen_poverty_low"), corruption("1"))),
    ("GNG_focus_expand_giant_enterprises", design("税制/财政收入/贫困", "巨企减税与扩权带来现金流，却压低劳动者所得", tax("business", "-0.018"), misc_income("0.04"), socdev("worsen_poverty_low"))),
    ("GNG_focus_under_shadow_of_Sony", design("稳定/腐败/南京关系", "索尼暂时压住抗议，但包庇交易伤害廉洁和华人观感", stability("0.012"), corruption("0.5"), china_opinion("-1"))),
    ("GNG_focus_matsushita_in_ZS", design("工业设备/财政收入/投资", "中山园区提高产能与收入，同时由政府承担前期成本", socdev("improve_industrial_equipment_low"), misc_income("0.045"), spend("0.065"))),
    ("GNG_focus_Ostrichs_tittytainment", design("财政收入/稳定/教育", "娱乐消费麻痹不满并赚钱，却侵蚀学习动力", misc_income("0.05"), stability("0.02"), socdev("worsen_academic_base_low"))),
    ("GNG_focus_lair_of_Hitachi_in_GZ", design("工业专长/财政收入/贫困", "日立总部扩张提升工业能力，却把劳工代价外包", socdev("improve_industrial_expertise_low"), misc_income("0.055"), socdev("worsen_poverty_low"))),
    ("GNG_focus_pleasure_of_Leviathan", design("增长/腐败/贫困", "利维坦式薄利多销制造高增长，同时扩大隐性剥削", gdp_growth("0.21"), corruption("1.25"), socdev("worsen_poverty_med"))),
    ("GNG_focus_lost_in_new_techno", design("科研/增长/腐败", "索尼松下技术合作确有成果，但利益输送继续加深", socdev("improve_research_facilities_low"), gdp_growth("0.15"), corruption("0.75"))),

    # Ibuka / Fujitsu: positive high-technology development with transition costs.
    ("GNG_focus_lunatic_of_ibuka", design("科研/财政/政治资本", "井深的宏图赢得资源，却要求庞大启动经费", socdev("improve_research_facilities_med"), spend("0.09"), pp(15))),
    ("GNG_focus_eliminate_backward", design("工业设备/增长/贫困", "淘汰落后产能提高效率，也制造结构性失业", socdev("improve_industrial_equipment_med"), gdp_growth("0.14"), socdev("worsen_poverty_low"))),
    ("GNG_focus_build_Joint_Campus", design("科研/教育/财政", "联合园区同时抬升研究设施和人才基础", socdev("improve_research_facilities_med"), socdev("improve_academic_base_low"), spend("0.105"))),
    ("GNG_focus_lete_technocrats_try", design("行政/腐败/政治资本", "技术官僚提升规划效率，也形成新的权力寻租点", socdev("improve_admin_efficiency_med"), corruption("0.35"), pp(20))),
    ("GNG_focus_pull_down_slums", design("科研空间/稳定/财政", "拆除城寨释放科研用地，却激起搬迁不满", socdev("improve_research_facilities_low"), stability("-0.015"), spend("0.065"))),
    ("GNG_focus_plan_to_build_SZ", design("城市建设/工业专长/财政", "深圳分区规划建设办公设施并培养产业组织能力", building(592, "offices", 1, 1), socdev("improve_industrial_expertise_low"), spend("0.08"))),
    ("GNG_focus_Great_Literacy_Campaign", design("教育/贫困/财政", "扫盲扩大人才池并提高底层就业能力", socdev("improve_academic_base_med"), socdev("improve_poverty_low"), spend("0.07"))),
    ("GNG_focus_digitization_government_work", design("行政/行政支出/稳定", "电子政务提高效率并节省岗位，同时触怒公务员", socdev("improve_admin_efficiency_med"), admin_costs("-0.018"), stability("-0.01"))),

    # Technology, trade and diplomacy branches after the coalition choices.
    ("GNG_focus_pursue_nnovation", design("科研/芯片竞赛/财政", "追求创新以科研设施和早期芯片竞争力为核心", socdev("improve_research_facilities_low"), scw("1", "0.01"), spend("0.045"))),
    ("GNG_focus_chip_cold_war", design("芯片竞赛/科研/财政", "正式资助富士通参与竞赛，规模与技术同步提升", scw("5", "0.025"), socdev("improve_research_facilities_low"), spend("0.085"))),
    ("GNG_focus_jackals_of_Central_Europe", design("芯片竞赛/腐败", "从中欧取得工艺与蓝图，也不可避免地使用灰色渠道", scw("2", "0.012"), corruption("0.45"))),
    ("GNG_focus_vultures_in_NA", design("芯片竞赛/财政收入/东京关系", "北美交流提升技术和订单，却使东京猜忌", scw("1", "0.022"), misc_income("0.025"), japan_approval("-1"))),
    ("GNG_focus_trade_with_ibuka", design("芯片竞赛/产业补贴", "出口补贴换取富士通技术与稳定研发利润", scw("4", "0.02"), misc_costs("0.012"))),
    ("GNG_focus_chip_bases_in_SZ", design("芯片竞赛/工业设备/财政", "深圳基地形成大规模制造能力，但建设极为昂贵", scw("8", "0.02"), socdev("improve_industrial_equipment_med"), spend("0.11"))),
    ("GNG_focus_the_first_port", design("财政收入/增长/港口", "胜利港扩大吞吐直接提高贸易收入和整体增长", misc_income("0.045"), gdp_growth("0.13"), building(326, "dockyard", 1, 1))),
    ("GNG_focus_splendor_of_Victory_Harbor", design("港口/财政收入/投资", "扩建香港港区以政府投资换取更高航运收入", building(326, "dockyard", 1), misc_income("0.035"), spend("0.055"))),
    ("GNG_focus_bridge_of_Sphere", design("基础设施/增长/东京关系", "南北运输走廊改善共荣圈物流并取悦东京", building(593, "infrastructure", 1), gdp_growth("0.10"), japan_approval("1"))),
    ("GNG_focus_global_free_trade_port", design("税制/财政收入/东京关系", "自由港减免企业税、扩大转口收入并挑战日本限制", tax("business", "-0.015"), misc_income("0.06"), japan_approval("-1"))),
    ("GNG_focus_expand_eduation_system", design("教育/科研/财政", "高校扩张同时改善学术基础与研究设施", socdev("improve_academic_base_med"), socdev("improve_research_facilities_low"), spend("0.09"))),
    ("GNG_focus_our_international_standing", design("政治资本/财政收入/东京关系", "独立外交提升声望与市场，却稍稍偏离东京", pp(35), misc_income("0.025"), japan_approval("-1"))),
    ("GNG_focus_be_in_the_Sphere", design("东京关系/南京关系/增长", "留在共荣圈换来市场与宗主认可，也疏远中国", japan_approval("3"), china_opinion("-2"), gdp_growth("0.09"))),
    ("GNG_focus_friend_in_Einheitspakt", design("财政收入/科研/东京关系", "德国关系兼有技术和市场价值，且不越过日德旧纽带", misc_income("0.04"), socdev("improve_research_facilities_low"), japan_approval("1"))),
    ("GNG_focus_wealth_of_OFN", design("财政收入/科研/东京关系", "OFN市场和科研资源丰厚，但明显冒犯日本", misc_income("0.055"), socdev("improve_research_facilities_low"), japan_approval("-2"))),
    ("GNG_focus_internationally_recognized", design("政治资本/财政收入/稳定", "广泛承认提升国家信誉、市场覆盖和内部信心", pp(50), misc_income("0.045"), stability("0.025"))),
    ("GNG_focus_prosperous_financial_fortune", design("增长/财政收入/腐败", "财运亨通显著改善财政，也给寻租者留下余地", gdp_growth("0.28"), misc_income("0.055"), corruption("0.35"))),

    # Security and police reform.
    ("GNG_focus_Pandoras_Box", design("南京关系/稳定/政治资本", "民族问题暴露后采取行动，但公开危机损害社会安定", china_opinion("-3"), stability("-0.02"), pp(20))),
    ("GNG_focus_shield_of_the_Rising_Sun", design("稳定/行政", "警务处承担战后治安重担，恢复基本秩序和协调能力", stability("0.015"), socdev("improve_admin_efficiency_really_low"))),
    ("GNG_focus_level_up_equipment", design("警械/军费", "采购杀伤性与支援警械提高战力，也增加维护成本", stockpile("infantry_equipment", 800), stockpile("support_equipment", 150), military_costs("0.012"))),
    ("GNG_focus_protect_your_own_life", design("防护装备/专业化/军费", "防护用品降低警员风险并推动训练标准化", stockpile("support_equipment", 250), socdev("improve_army_professionalism_low"), military_costs("0.008"))),
    ("GNG_focus_and_the_lives_of_others", design("非致命执法/稳定", "非致命警械兼顾专业化和公众信任", socdev("improve_army_professionalism_low"), stability("0.012"))),
    ("GNG_focus_against_criminal_offences", design("廉洁/稳定", "集中打击刑事犯罪降低地下寻租并恢复安全感", corruption("-0.5"), stability("0.01"))),
    ("GNG_focus_expanding_Criminal_Department", design("行政/行政支出", "刑事部门专业分科提高效率，但需要长期预算", socdev("improve_admin_efficiency_low"), admin_costs("0.012"))),
    ("GNG_focus_century_of_science", design("刑侦科研/财政", "法医和工程鉴定需要研究设施及专项拨款", socdev("improve_research_facilities_low"), spend("0.03"))),
    ("GNG_focus_into_the_community", design("稳定/廉洁", "社区警务以日常信任减少小规模腐败与冲突", stability("0.018"), corruption("-0.25"))),
    ("GNG_focus_harmonious_and_safe", design("行政/贫困/稳定", "预防性治理处理社区风险并扶助边缘人群", socdev("improve_admin_efficiency_really_low"), socdev("improve_poverty_low"), stability("0.014"))),
    ("GNG_focus_reject_PGD", design("廉洁/财政收入/稳定", "扫黄赌毒改善秩序，却切断一部分灰色财政来源", corruption("-0.4"), misc_income("-0.01"), stability("0.008"))),
    ("GNG_focus_loyalty_and_courage", design("稳定/指挥/廉洁", "阶段性治安成果提高警民信心和警队协同", stability("0.03"), command_power(12), corruption("-0.5"))),
    ("GNG_focus_establishment_PRU", design("专业化/人力/军费", "警备部门获得专门编制与人员，也形成固定支出", socdev("improve_army_professionalism_low"), manpower(8000), military_costs("0.015"))),
    ("GNG_focus_special_skills_units", design("训练/科研/财政", "反爆、救援与CBRN部队依赖训练和技术装备", army_xp(7), socdev("improve_research_facilities_low"), spend("0.025"))),
    ("GNG_focus_territorial_support_force", design("指挥/装备/军费", "地域支援部队强化机动处置并消耗持续预算", command_power(15), stockpile("support_equipment", 180), military_costs("0.01"))),
    ("GNG_focus_watching_YOU", design("政治资本/南京关系/腐败", "公安监控提高政府控制力，却损害华人关系并制造黑箱", pp(35), china_opinion("-2"), corruption("0.5"))),
    ("GNG_focus_Secret_Force_May", design("政治资本/腐败/稳定", "秘密实动部队提供隐蔽力量，也让法外权力扩张", pp(25), corruption("0.75"), stability("-0.005"))),
    ("GNG_focus_force_major_terrorism", design("战意/指挥/稳定", "反恐精锐提高强制处置能力，社会则因威胁感到不安", war_support("0.025"), command_power(20), stability("-0.01"))),
    ("GNG_focus_anti_black_department", design("廉洁/财政收入", "独立反黑部门压缩犯罪寻租并追回部分非法资金", corruption("-1"), misc_income("0.015"))),
    ("GNG_focus_police_tactics", design("廉洁/政治资本/战意", "顶上作战摧毁顽固团伙并展示政府决心", corruption("-0.75"), pp(20), war_support("0.01"))),
    ("GNG_focus_Strike_hard_at_transnational_crime", design("财政收入/廉洁/东京关系", "跨国执法追回外流财富，并依赖共荣圈协作", misc_income("0.03"), corruption("-0.6"), japan_approval("1"))),
    ("GNG_focus_gng_good_order", design("稳定/行政/贫困", "恢复正常秩序后，政府从紧急镇压转向文官治理", stability("0.05"), socdev("improve_admin_efficiency_med"), socdev("improve_poverty_low"))),
    ("GNG_focus_peace_and_prosperity", design("军队专业化/稳定/军费", "广东自主防务体系成熟，并逐步降低紧急军费", socdev("improve_army_professionalism_med"), stability("0.04"), military_costs("-0.015"))),
    ("DOP_GNG_focus_exquisite_equipment", design("装备/训练", "精湛装备为新军补足武器与使用经验", stockpile("infantry_equipment", 2500), stockpile("support_equipment", 400), army_xp(12))),
]
